apiVersion: v1
kind: Service
metadata:
  name: kanban-board-app-service
spec:
  selector:
    app: kanban-board-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
  type: LoadBalancer
